# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 075f6a51906d8a039e6bf883a486f6c9b79bda409b1d49cafa3b029e00a87a303f5df3a3cde313f44c2489f2d69431bec121ade1c4f40f785311cc660232661a

test:
  secret_key_base: 6962382b9432a42c69aae81271a02e342c62e58d8ff5a3143a2a6d7045050c445b74d98fb766733aade76993e9d24a0c5cb8013ace1e1425f2f9a4f20f2c8f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
